### ISSUE TITLE
Home version 1 - Apply Server Driven UI

### ISSUE THREAD

**Issue by great-park** [hellokitty-coding-club/LGTM-Backend#11]
### 문제 상황

저희 팀은 네이티브 안드로이드 앱으로 프론트엔드를 개발합니다. 
웹과 달리 앱의 경우 빌드와 배포로 부터 자유롭지 못하여, 유연한 UI를 제공하기 어렵습니다. 
만약 새로운 기능을 개발하거나 기존 버전에서 잘못된 위치에 버튼을 배치한 채 스토어에 앱을 배포했다면, 사용자가 스스로 스토어에 들어가서 새로운 버전의 앱을 받기 전까지는 이를 해결할 방법이 없습니다.

좀 더 나아가서, 이러한 특성은 A/B Test를 수행하는데 큰 걸림돌이 됩니다. 
사용자를 A,B 그룹으로 나누고 각 그룹에게 서로 다른 UI를 제공하여 가장 적절한 UI를 선정하는 A/B test를 진행하기 위해서는 "유연한 UI"가 제공되어야 합니다. 하지만, 네이티브 안드로이드 앱의 경우, 이것이 어렵습니다. 

또한, 저희 팀은 사용자의 활동을 추적할 수 있는 EventLog를 심어서 success metric을 분석하고 이를 개선하기 위한 A/B test를 진행해야 합니다.
이때, 로깅 서버로 보내줄 eventlog의 목록이 누락될 수 있고, 마찬가지로 사용자가 업데이트하기 전까지 데이터 수집이 어려울 것입니다.

### 해결 방법 - Server Driven UI 설계 적용
네이티브 모바일 앱을 개발하면서 이러한 문제점들을 해결하기 위해서 Server Driven UI 설계를 도입하기로 결정했습니다. 

Server Driven UI는 서버에서 동적으로 클라이언트의 UI를 구성하는 설계 방식입니다. 저희 팀에서는 미리 각 화면을 구성하는 Component를 다시 세부적으로 content으로 나누었고, 각 content에는 View Type, theme, 데이터가 들어가도록 설계했습니다.

아래는 저희 팀이 홈화면에 대해서 정의한 View type 예시입니다.
(개발 과정에서 View Type의 정의가 변경될 수 있습니다. 참고만 부탁드립니다.)
![image](https://github.com/hellokitty-coding-club/LGTM-Backend/assets/83508073/7d60b1df-86ba-4fd9-942b-cec1ded70784)

이제 클라이언트는 각 View type에 대해서 어떤 UI를 그릴 지만 구현하고, 서버에서 content들을 API response로 내려주면, 서버에서 UI를 동적으로 컨트롤할 수 있게 됩니다.

이로써 다음 사항들이 개선되었습니다. 
- 동적인 UI 구성을 통해 빠르고 정확한 A/B test 진행 가능
- 구버전 유지를 위한 서버 분기 제거
- event log 목록이 추가, 제거 되더라도 동적으로 목록을 내려줌으로써 log 손실을 최소화

현재는 홈화면에 대해서 Server Driven UI 설계를 적용하여 개발하고자 합니다. 
또한 Event log는 명확한 정의가 이뤄진 후에 추가할 계획입니다. 

## To-do

- [x] 진행 중인 미션 조회 비즈니스 로직 구현
- [x] 전체 미션 조회 비즈니스 로직 구현
- [x] 맞춤 추천 미션 조회 비즈니스 로직 구현
- [x] SDUI를 효율적으로 관리하기 위한 객체 설계
- [x] 테스트 코드 작성
