### ISSUE TITLE
Home API V3

### ISSUE THREAD

**Issue by great-park** [hellokitty-coding-club/LGTM-Backend#122]
## Description
home api에 몇가지 사항을 더해 리팩토링하겠습니다. 곧 서비스를 출시하고 유저가 유입되기 전에 A/B Test를 진행할 항목들을 정리하기 위해 최대한 빠르게 개발하도록 하겠습니다. 

## To-do
- [ ] A/B Test 사용자 그룹 분배 로직 - 전략 패턴을 사용하여 각 테스트에 맞는 전략을 끼워서 동작하도록 설계
- [ ] 그룹 분배 전략 관련 도메인 개발
- [ ] Home api - A/B Test 로직과 연결
