### ISSUE TITLE
Kafka Producer&Consumer

### ISSUE THREAD

**Issue by ray-yhc** [hellokitty-coding-club/LGTM-Backend#33]
### 요구사항

- [x] 채팅 메시지 브로커 : 채팅 메시지 전송 및 서버 간 공유
- [x] 사용자 로그 수집 : 사용자의 활동에 따른 로그 수집
- [x] 클라우드 VM 모니터링 : application server와 컴퓨팅 자원의 상태 모니터링

### 고가용성 카프카 클러스터 구축
    
위의 요구사항을 충족시키기 위해 카프카 클러스터를 구축했습니다.

<img width="825" alt="image" src="https://github.com/hellokitty-coding-club/LGTM-Backend/assets/61899645/6bdee047-076e-46b3-bd22-6b1c9a545f1c">

카프카를 도입한 이유는 다음과 같습니다.

- 토픽을 통한 확장성 : 토픽마다 서로 다른 pub/sub 작업들을 모두 하나의 클러스터로 관리할 수 있습니다. 토픽들이 같은 클러스터를 사용하면서도 각기 다른 정책(순서 보장 / 단 한번만 전송 / isr/ 데이터 무결성 보장 등)을 적용할 수 있습니다.
    
    이를 통해 채팅에서는 단 한번만 전송되며 무결성이 강력히 보장되도록,
    
    로깅에서는 중복,무결성에 대해 에러를 어느 수준 허용하며 성능을 향상시키도록 설정할 수 있었습니다.
    
- 수평 확장에 용이 : 수평 확장에 한계가 있는 기존 message queue, 샤드별로 노드 수를 확장해야 하는 redis cluster에 비해 확장에 용이합니다. 클러스터 내의 브로커 수를 확장하면 모든 토픽에 대해서 확장이 가능합니다. 또한 노드를 서로 다른 가용 영역에 배치함으로써 고가용성 클러스터를 구축할 수 있습니다.
- 브로커와 컨슈머의 트래픽 조절 : kafka는 컨슈머의 상태인 offset을 클라이언트에서 관리하므로 브로커와 컨슈머의 처리량을 균등하게 분담할 수 있습니다. 많은 컨슈머가 연결되더라도 브로커의 부담이 크게 증가하지 않으며, 컨슈머에서 데이터 처리를 하지 못하더라도 메시지가 손실되지 않습니다.
이는 컨슈머가 메시지를 읽은 후 메시지가 삭제되거나, 브로커에서 컨슈머의 상태를 모두 관리하는 등의 기존 message queue보다 이점이 있다고 판단했습니다.

고가용성 클러스터 구축을 위해 세 개의 가용영역에서 클러스터 노드를 운영했습니다.

- 주키퍼 앙상블 구성 : 과반수의 쿼럼 노드가 동작하기 위해서 최소 3개의 노드가 필요합니다.
- 카프카 브로커 : leader 파티션과 follower 파티션이 항상 동시에 운영되도록 하기 위해 3개 이상의 노드가 필요합니다.

## To-do
- [ ]

**Comment by great-park** [comment]
# 토픽 구성
현재 3개의 브로커에서 6개의 토픽을 구축할 계획입니다. 
- user-log : 앱 사용자의 로그를 관리하는 토픽입니다. dev, prod, test 총 3개로 운영 중입니다.
- chatting-log : 채팅 메시지를 관리하는 토픽입니다. dev, prod, test 총 3개로 운영 중입니다.

현재까지는 user-log 토픽에 대한 기능만 개발 중입니다.
# user-log 토픽 관련
클라이언트와 합의하여 다음과 같이 사용자 로그 형식을 정의하였습니다.
```json
{
	"eventLogName" : "missionClick",
	"screenName" : "home",
	"logVersion" : 2,
	"logData" : {
		"periodDays" : 5,
		"missionPrice" : 20000,
		"techTags" : ["Android", "Bacnekd"]
	}
}
```
eventLogName, screenName, logVersion은 모든 사용자 로그가 가지는 공동 속성이고, 
logData는 각 사용자 로그 종류마다 다양한 형식을 가질 수 있게 설계할 계획입니다.

위 형식으로 DTO를 만들고, 카프카 producer, consumer에 직렬화 설정을 진행하겠습니다.

카프카 클러스터 구축은 #87 해당 이슈에 적힌 가이드를 따릅니다.

**Comment by great-park** [comment]
# 로그 저장 관련

현재, 카프카 consumer에서 단순히 spring 서버용 로그만 찍고 메시지를 저장하고 있지 않은 상태이므로, NoSQL에 저장하는 로직을 추가하겠습니다. 

AWS DynamoDB를 사용하여 사용자 로그 데이터를 일단 DynamoDB에 쌓아 두고, 추후 분석 및 시각화 기능을 연결할 예정입니다.

**Comment by great-park** [comment]
# DB 변경
DynamoDB에서 MongoDB로 변경하겠습니다. 

DynamoDB를 사용하지 않는 이유는 다음과 같습니다.
- spring과 연동이 불편함. 연동은 됐으나 지원되는 기능이 한정적이다.
- 비용이 비쌈
- Log data를 시각화하기 위해서 다른 도구를 연동하기가 불편하다. 

MongoDB로 전환하여 위와 같은 문제점들을 해결하겠습니다.
