### ISSUE TITLE
Grouping User For A/B test with SDUI

### ISSUE THREAD

**Issue by great-park** [hellokitty-coding-club/LGTM-Backend#47]
## Description
A/B Test를 진행하기 위한 User 그룹핑 로직을 설계합니다. 
SDUI 덕분에 유저의 그룹 서비스 로직으로 넘기면 자동으로 해당 그룹에 대한 로직이 실행되도록 할 수 있습니다.

### 현재 문제점
현재 홈화면 api에서 version이라는 불명확한 변수로 sdui를 컨트롤하고 있습니다. 

### 개선 방향
따라서 유저의 그룹 정보를 db나 캐시에서 관리하고 이를 기반으로 sdui를 구성해야 합니다.

## To-do
- [x] 유저 그룹 정보 설계
- [x] Db나 캐시에서 그룹 정보 관리
- [x] version 대신 그룹 정보로 sdui 구성
- ... 

## ETC
(기타 사항이 있다면 추가해주세요.)
